# Generated by Django 2.2.4 on 2020-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_flats', to='property.Person'),
        ),
    ]
