# Generated by Django 2.2.4 on 2020-12-06 17:06

from django.db import migrations
import phonenumbers


class Migration(migrations.Migration):

    def make_pure_phone(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            try:
                phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            except phonenumbers.NumberParseException:
                phone = None

            if phonenumbers.is_valid_number(phone):
                flat.owner_pure_phone = phonenumbers.format_number(
                    phone, phonenumbers.PhoneNumberFormat.E164
                )
                flat.save()


    def move_backward(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            flat.owner_pure_phone = None
            flat.save()

    dependencies = [
        ('property', '0007_auto_20201206_2005'),
    ]

    operations = [
        migrations.RunPython(make_pure_phone, move_backward)
    ]
