# Generated by Django 2.2.4 on 2020-12-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    def make_many_to_many(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        for flat in Flat.objects.all():
            owner, created = Owner.objects.get_or_create(
                name=flat.owner,
                pure_phone=flat.owner_pure_phone,
                defaults={
                    'phonenumber': flat.owners_phonenumber,
                }
            )
            if created:
                owner.flat.add(flat)
            else:
                owner.flat.set([flat])


    def move_backward(apps, schema_editor):
        Owner = apps.get_model('property', 'Owner')
        for owner in Owner.objects.all():
            owner.flat.clear()

    dependencies = [
        ('property', '0010_auto_20201206_2234'),
    ]

    operations = [
        migrations.RunPython(make_many_to_many, move_backward)
    ]
